# 服务器配置
server:
  application:
    name: ch
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

# 日志配置
logging:
  config: classpath:logback-spring.xml

# 文件上传配置
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  # 开发工具配置
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,public/**
    livereload:
      enabled: true
  # 配置 ANSI 输出
  output:
    ansi:
      # 有三个可选值：DETECT / ALWAYS / NEVER
      # DETECT - 检查终端是否支持 ANSI，是的话就启用彩色输出，默认值
      # ALWAYS - 不检查，总是彩色输出
      # NEVER - 禁用彩色输出
      enabled: ALWAYS