# 服务器配置
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

# 日志配置
logging:
  level:
    root: INFO
    com.example.demo01: DEBUG

# 文件上传配置
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  # 开发工具配置
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,public/**
    livereload:
      enabled: true